name: Deploy to VPS

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    env:
      image_name: ms-sender-notification
      image_version: latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update password of redis
        run: sed -i 's/<redis_password>/${{ secrets.REDIS_PASSWORD }}/' src/main/resources/application.yml

      - name: Update port of redis
        run: sed -i 's/<redis_port>/${{ secrets.REDIS_PORT }}/' src/main/resources/application.yml

      - name: Update redis host
        run: sed -i 's/<host_redis>/${{ secrets.VPS_IP }}/' src/main/resources/application.yml

      - name: Update sender mail user
        run: sed -i 's/<sender_mail_user>/${{ secrets.SENDER_MAIL_USER }}/' src/main/resources/application.yml

      - name: Update sender mail password
        run: sed -i 's/<sender_mail_password>/${{ secrets.SENDER_MAIL_PASSWORD }}/' src/main/resources/application.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build project and verify test
        run: mvn clean install

      - name: Push image DOCKER
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}
          tags: ${{ env.image_version }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/administrator/applications/shipping-shalom
            echo ${{ secrets.VPS_PASSWORD }} | sudo docker stop ${{ env.image_name }}
            echo ${{ secrets.VPS_PASSWORD }} | sudo docker rm ${{ env.image_name }}
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:${{ env.image_version }}
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker compose up -d --build
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker system prune -a